services:
  catalogdb:
    image: postgres
  
  basketdb:
    image: postgres
  
  distributedcache:
    image: redis
  
  orderdb:
    image: mcr.microsoft.com/mssql/server
  
  messagebroker:
    image: rabbitmq:management
  
  basket.api:
    image: basket.api
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
  
  discount.grpc:
    image: discount.grpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile
  
  catalog.api:
    image: catalog.api
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
  
  ordering.api:
    image: ordering.api
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile
  
  yarpapigateway:
    image: yarpapigateway
    build:
      context: .
      dockerfile: ApiGateways/YarpApiGateway/Dockerfile
  
volumes:
  postgres_catalog:  
  postgres_basket:
